<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;
use DataTime;

class AbandonedBicyclesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('abandoned_bicycles')->insert([
            [
                'user_id' => 1,
                'model' => 'シティサイクル',
                'manufacturer' => 'Panasonic',
                'model_name' => 'Model-A1',
                'frame_num' => 'FRM-2000',
                'color' => 'Red',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211111',
                'found_at' => now()->subDays(1),
                'found_location' => '大阪市北区',
                'image_path' => 'images/bikeA1.jpg',
                'features' => '前かご付き',
                'other' => 'ベルが大きい',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'model' => 'ロードバイク',
                'manufacturer' => 'GIANT',
                'model_name' => 'Model-A2',
                'frame_num' => 'FRM-2001',
                'color' => 'Blue',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211112',
                'found_at' => now()->subDays(3),
                'found_location' => '名古屋市中区',
                'image_path' => 'images/bikeA2.jpg',
                'features' => 'ドリンクホルダー付き',
                'other' => 'スタンドが固め',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'model' => 'ミニベロ',
                'manufacturer' => 'Panasonic',
                'model_name' => 'Model-A3',
                'frame_num' => 'FRM-2002',
                'color' => 'Silver',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211113',
                'found_at' => now()->subDays(4),
                'found_location' => '東京都中野区',
                'image_path' => 'images/bikeA3.jpg',
                'features' => '折りたたみ式',
                'other' => 'ブレーキに難あり',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'model' => 'シティサイクル',
                'manufacturer' => 'Panasonic',
                'model_name' => 'Model-A4',
                'frame_num' => 'FRM-2003',
                'color' => 'Red',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211114',
                'found_at' => now()->subDays(6),
                'found_location' => '札幌市中央区',
                'image_path' => 'images/bikeA4.jpg',
                'features' => 'サドルが高め',
                'other' => 'ペダルがカスタム品',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'model' => 'ロードバイク',
                'manufacturer' => 'BRIDGESTONE',
                'model_name' => 'Model-A5',
                'frame_num' => 'FRM-2004',
                'color' => 'Blue',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211115',
                'found_at' => now()->subDays(7),
                'found_location' => '大阪市北区',
                'image_path' => 'images/bikeA5.jpg',
                'features' => '前かご付き',
                'other' => 'ハンドルにキズあり',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'model' => 'ミニベロ',
                'manufacturer' => 'GIANT',
                'model_name' => 'Model-A6',
                'frame_num' => 'FRM-2005',
                'color' => 'Silver',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211116',
                'found_at' => now()->subDays(2),
                'found_location' => '名古屋市中区',
                'image_path' => 'images/bikeA6.jpg',
                'features' => '太めのタイヤ',
                'other' => 'チェーンが金色',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'model' => 'シティサイクル',
                'manufacturer' => 'Panasonic',
                'model_name' => 'Model-A7',
                'frame_num' => 'FRM-2006',
                'color' => 'Red',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211117',
                'found_at' => now()->subDays(10),
                'found_location' => '東京都中野区',
                'image_path' => 'images/bikeA7.jpg',
                'features' => 'ベルが大きい',
                'other' => 'サドルが高め',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'model' => 'ロードバイク',
                'manufacturer' => 'Panasonic',
                'model_name' => 'Model-A8',
                'frame_num' => 'FRM-2007',
                'color' => 'Blue',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211118',
                'found_at' => now()->subDays(5),
                'found_location' => '札幌市中央区',
                'image_path' => 'images/bikeA8.jpg',
                'features' => '折りたたみ式',
                'other' => 'スタンドが固め',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'model' => 'ミニベロ',
                'manufacturer' => 'BRIDGESTONE',
                'model_name' => 'Model-A9',
                'frame_num' => 'FRM-2008',
                'color' => 'Silver',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211119',
                'found_at' => now()->subDays(8),
                'found_location' => '大阪市北区',
                'image_path' => 'images/bikeA9.jpg',
                'features' => 'ドリンクホルダー付き',
                'other' => 'ハンドルにキズあり',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'model' => 'シティサイクル',
                'manufacturer' => 'Panasonic',
                'model_name' => 'Model-A10',
                'frame_num' => 'FRM-2009',
                'color' => 'Red',
                'prefecture' => '東京都',
                'bouhan_num' => 'BHN-211120',
                'found_at' => now()->subDays(9),
                'found_location' => '東京都中野区',
                'image_path' => 'images/bikeA10.jpg',
                'features' => '太めのタイヤ',
                'other' => 'ブレーキに難あり',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
